// ─────────────────────────────────────────────────────────────────────────────
// SERVER CONTENT CONFIGURATION
// GENERATED by the CodeMax pipeline — edit to customise brand copy used in emails.
// ─────────────────────────────────────────────────────────────────────────────

export const CONTENT = {
  brand: {
    name:    'AppTemplate',        // Business / app name shown in email headers and subjects
    tagline: 'Your tagline here.', // One-sentence value prop shown in email footers
  },
} as const
