
# project_6d265d52-4cb4-432e-8d31-1fccfb5006ef
location /preview/6d265d52-4cb4-432e-8d31-1fccfb5006ef/ {
    set $upstream codemax_preview_6d265d52-4cb4-432e-8d31-1fccfb5006ef;
    proxy_pass http://$upstream:3001/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}


# project_ce02f8b7-de44-4d65-99e1-b5b4845b76f1
location /preview/ce02f8b7-de44-4d65-99e1-b5b4845b76f1/ {
    set $upstream codemax_preview_ce02f8b7-de44-4d65-99e1-b5b4845b76f1;
    proxy_pass http://$upstream:3001/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}


# project_dad23fb6-f2c0-42cf-8448-e36c67174de2
location /preview/dad23fb6-f2c0-42cf-8448-e36c67174de2/ {
    set $upstream codemax_preview_dad23fb6-f2c0-42cf-8448-e36c67174de2;
    proxy_pass http://$upstream:3001/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

# project_42e4e7cb-81af-4b89-a828-b6a04dd1fb0a
location /preview/42e4e7cb-81af-4b89-a828-b6a04dd1fb0a/ {
    set $upstream codemax_preview_42e4e7cb-81af-4b89-a828-b6a04dd1fb0a;
    proxy_pass http://$upstream:3001/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

# project_ba78d8b0-3598-482e-99f4-fb58068b3c4a
location /preview/ba78d8b0-3598-482e-99f4-fb58068b3c4a/ {
    set $upstream codemax_preview_ba78d8b0-3598-482e-99f4-fb58068b3c4a;
    proxy_pass http://$upstream:3001/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

# project_0255f176-aaaa-470a-9d9b-53658a4ab482
location /preview/0255f176-aaaa-470a-9d9b-53658a4ab482/ {
    set $upstream codemax_preview_0255f176-aaaa-470a-9d9b-53658a4ab482;
    proxy_pass http://$upstream:3001/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
