package com.reuzenpanda.codemax.tasks.pipeline.generators;

import com.reuzenpanda.codemax.tasks.pipeline.model.AppSpecification;
import com.reuzenpanda.codemax.tasks.pipeline.model.BrandingSpec;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

/**
 * Generates content.ts (client + server) and patches globals.css.
 * Deterministic — no AI call needed. All values come from AppSpecification.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class BrandingGenerator {

    public void generate(Path projectDir, AppSpecification spec,
                          Map<String, String> answers) throws IOException {
        BrandingSpec b = spec.branding() != null ? spec.branding() : defaultBranding(spec.appName());
        String name        = escapeTs(spec.appName());
        String tagline     = escapeTs(b.tagline().isBlank()       ? "Your tagline here." : b.tagline());
        String color       = b.accentColorRgb().isBlank()         ? "99 102 241" : b.accentColorRgb();
        String headline    = escapeTs(b.heroHeadline().isBlank()    ? "Your headline here." : b.heroHeadline());
        String subheadline = escapeTs(b.heroSubheadline().isBlank() ?
            "A short sentence explaining what the app does and who it is for." : b.heroSubheadline());
        String contactEmail = escapeTs(answers.getOrDefault("contact_email", "hello@example.com"));

        StringBuilder featItems = new StringBuilder();
        List<Map<String, String>> items = b.featureItems();
        if (items == null || items.isEmpty()) {
            featItems.append(defaultFeatureItems());
        } else {
            for (Map<String, String> f : items) {
                featItems.append("      { icon: '").append(escapeTs(f.getOrDefault("icon", "Zap")))
                         .append("', title: '").append(escapeTs(f.getOrDefault("title", "Feature")))
                         .append("', description: '").append(escapeTs(f.getOrDefault("description", "Feature description.")))
                         .append("' },\n");
            }
        }

        String contentTs = buildClientContent(name, tagline, color, headline, subheadline, featItems.toString(), contactEmail);
        String serverContentTs = buildServerContent(name, tagline);

        save(projectDir, "src/config/content.ts", contentTs);
        save(projectDir, "server/src/config/content.ts", serverContentTs);

        // Patch globals.css for static CSS fallback before JS runs
        String css = loadFile(projectDir, "src/styles/globals.css");
        if (!css.isBlank()) {
            save(projectDir, "src/styles/globals.css",
                css.replaceAll("--color-accent:\\s*[0-9 ]+;", "--color-accent: " + color + ";"));
        }
        log.info("BrandingGenerator: content.ts generated for '{}'", name);
    }

    // ── Content builders ─────────────────────────────────────────────────────

    private String buildClientContent(String name, String tagline, String color,
                                       String headline, String subheadline,
                                       String featItems, String contactEmail) {
        return
            "// GENERATED by the CodeMax pipeline — edit freely to customise the app copy.\n" +
            "// All user-facing text and the accent color live here.\n" +
            "// Accent color is an RGB triple (no commas, e.g. '20 184 166' for teal).\n\n" +
            "export const CONTENT = {\n" +
            "  brand: {\n" +
            "    name:        '" + name    + "',\n" +
            "    tagline:     '" + tagline + "',\n" +
            "    accentColor: '" + color   + "',\n" +
            "  },\n" +
            "  hero: {\n" +
            "    badge:        '\\u2726 " + name + " — Now available',\n" +
            "    headline:     '" + headline    + "',\n" +
            "    subheadline:  '" + subheadline + "',\n" +
            "    ctaPrimary:   'Get started free',\n" +
            "    ctaSecondary: 'See how it works',\n" +
            "    footnote:     'No credit card required.',\n" +
            "  },\n" +
            "  features: {\n" +
            "    label:    'Features',\n" +
            "    title:    'Everything you need.',\n" +
            "    subtitle: '" + tagline + "',\n" +
            "    items: [\n" +
            featItems +
            "    ],\n" +
            "  },\n" +
            "  about: {\n" +
            "    label:       'About',\n" +
            "    title:       'Built for you.',\n" +
            "    description: '" + tagline + "',\n" +
            "    stats: [\n" +
            "      { value: '\\u2014', label: 'Stat one'   },\n" +
            "      { value: '\\u2014', label: 'Stat two'   },\n" +
            "      { value: '\\u2014', label: 'Stat three' },\n" +
            "      { value: '\\u2014', label: 'Stat four'  },\n" +
            "    ],\n" +
            "    bullets: [\n" +
            "      'Key benefit or differentiator one',\n" +
            "      'Key benefit or differentiator two',\n" +
            "      'Key benefit or differentiator three',\n" +
            "      'Key benefit or differentiator four',\n" +
            "    ],\n" +
            "  },\n" +
            "  work: {\n" +
            "    label:    'Work',\n" +
            "    title:    'How it works',\n" +
            "    subtitle: 'Replace these cards with your own case studies or use-case examples.',\n" +
            "    projects: [\n" +
            "      { tag: 'Step 1', name: 'Sign up',  description: 'Create your account in seconds.',         year: '' },\n" +
            "      { tag: 'Step 2', name: 'Set up',   description: 'Connect your data or configure the app.', year: '' },\n" +
            "      { tag: 'Step 3', name: 'Ship it',  description: 'Go live and start seeing results.',       year: '' },\n" +
            "    ],\n" +
            "  },\n" +
            "  contact: {\n" +
            "    label:    'Contact',\n" +
            "    title:    'Get in touch',\n" +
            "    subtitle: \"Have a question or want to work together? Fill in the form and we'll get back to you.\",\n" +
            "    email:    '" + contactEmail + "',\n" +
            "    location: 'Your City, Country',\n" +
            "    hours:    'Mon\\u2013Fri, 9 am\\u20136 pm',\n" +
            "    success:  \"Message sent! We'll reply within 1 business day.\",\n" +
            "  },\n" +
            "  testimonials: {\n" +
            "    label: 'Testimonials',\n" +
            "    title: 'What people are saying',\n" +
            "    items: [\n" +
            "      { quote: 'Replace this with a real customer quote about your product.', author: 'First Last', role: 'Role, Company' },\n" +
            "      { quote: 'Replace this with a real customer quote about your product.', author: 'First Last', role: 'Role, Company' },\n" +
            "      { quote: 'Replace this with a real customer quote about your product.', author: 'First Last', role: 'Role, Company' },\n" +
            "    ],\n" +
            "  },\n" +
            "  footer: {\n" +
            "    tagline:    '" + tagline + "',\n" +
            "    bottomNote: 'Built with React + Tailwind CSS',\n" +
            "  },\n" +
            "} as const\n";
    }

    private String buildServerContent(String name, String tagline) {
        return "// GENERATED by the CodeMax pipeline.\n" +
            "export const CONTENT = {\n" +
            "  brand: {\n" +
            "    name:    '" + name    + "',\n" +
            "    tagline: '" + tagline + "',\n" +
            "  },\n" +
            "} as const\n";
    }

    private String defaultFeatureItems() {
        return
            "      { icon: 'Zap',      title: 'Feature one',   description: 'Short benefit statement for feature one.'   },\n" +
            "      { icon: 'Shield',   title: 'Feature two',   description: 'Short benefit statement for feature two.'   },\n" +
            "      { icon: 'Globe',    title: 'Feature three', description: 'Short benefit statement for feature three.' },\n" +
            "      { icon: 'Sparkles', title: 'Feature four',  description: 'Short benefit statement for feature four.'  },\n" +
            "      { icon: 'Lock',     title: 'Feature five',  description: 'Short benefit statement for feature five.'  },\n" +
            "      { icon: 'Palette',  title: 'Feature six',   description: 'Short benefit statement for feature six.'   },\n";
    }

    private BrandingSpec defaultBranding(String appName) {
        return new BrandingSpec("99 102 241", "Your tagline here.",
            "Your headline here.",
            "A short sentence explaining what the app does and who it is for.",
            List.of());
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private String escapeTs(String s) {
        return s == null ? "" : s.replace("\\", "\\\\").replace("'", "\\'");
    }

    private void save(Path projectDir, String relativePath, String content) throws IOException {
        Path dest = projectDir.resolve(relativePath);
        Files.createDirectories(dest.getParent());
        Files.writeString(dest, content);
    }

    private String loadFile(Path projectDir, String relativePath) {
        try {
            Path p = projectDir.resolve(relativePath);
            return Files.exists(p) ? Files.readString(p) : "";
        } catch (IOException e) {
            return "";
        }
    }
}
